### ISSUE TITLE
perldoc-jp/translation リポジトリへの統合を行いたい

### ISSUE THREAD

**Issue by kfly8** [jpa/Moose-Doc-JA#1]
お世話になっています。JPAのkobaken です。

OSDN.net にあった perldoc.jp の翻訳データが、 https://github.com/perldoc-jp/translation へ先日、統合されました。
これを背景に、このリポジトリも https://github.com/perldoc-jp/translation へ統合を行いたいです。
https://github.com/jpa/MooseX-Getopt-Doc-JA も合わせて統合できると、perldoc.jpで利用する翻訳データは、perldoc-jp/translation のみとなり、perldoc.jpの翻訳データの取り込み処理がメンテナンスしやすくなるのではないかと思っています。

いかがでしょうか？ @lestrrat @charsbar

**Comment by lestrrat** [comment]
私からは特に問題ありませんー

**Comment by kfly8** [comment]
. @charsbar さんからのお返事はまだいただけていないですが、
貢献の履歴は残す形で移行するので、おそらく問題はないと思う（あっても切り戻せる）ので、やってしまいます！

**Comment by kfly8** [comment]
https://github.com/perldoc-jp/translation/pull/110

統合を行いました！
